# Harmony Jekyll theme general configurations 

# Base URL
baseurl: ""

# Site live URL
url: http://herval.github.io

# Localhost 
# url: http://127.0.0.1:4000  

harmony:
  name: Herval Freire
  # Little description about your site
  description: "Software, hardware, peopleware"
  meta_description: "Software, hardware, peopleware"
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Herval Freire
    email: me@hervalicio.us
    url: http://herval.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-1184658-15

  # Profile links, leave blank to ignore
  social: 
    github: herval
    twitter: herval
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
